[package]
name = "node-predict"
version = "0.1.0"
authors = ["XPredictMarket"]
description = "A new FRAME-based Substrate node, ready for hacking."
edition = "2018"
license = "Apache-2.0"
build = "build.rs"
repository = "https://github.com/XPredictMarket/NodePredict"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-predict"

[dependencies]
structopt = "0.3.8"
hex-literal = "0.3.1"
serde_json = "1.0.64"

sc-cli = { version = "0.9.0", features = ["wasmtime"] }
sp-core = { version = "3.0.0" }
sc-executor = { version = "0.9.0", features = ["wasmtime"] }
sc-service = { version = "0.9.0", features = ["wasmtime"] }
sc-telemetry = { version = "3.0.0" }
sc-keystore = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sc-transaction-pool = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }
sc-consensus-aura = { version = "0.9.0" }
sp-consensus-aura = { version = "0.9.0" }
sp-consensus = { version = "0.9.0" }
sc-consensus = { version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sp-finality-grandpa = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sp-blockchain = { version = "3.0.0" }
sp-block-builder = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }
substrate-frame-rpc-system = { version = "3.0.0" }
pallet-transaction-payment-rpc = { version = "3.0.0" }
# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "3.0.0" }
frame-benchmarking-cli = { version = "3.0.0" }

predict-runtime = { version = "0.1.0", path = "../runtime" }
proposals-info-rpc = { version = "0.1.0", path = "../pallets/proposals/rpc" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0" }

[features]
default = []
runtime-benchmarks = ["predict-runtime/runtime-benchmarks"]
